Chore(Next-Gen): enable pre-commits for `CAREamistV2` (#833)
## Description

Following https://github.com/CAREamics/careamics/pull/827, this PR
enables pre-commit hooks for `CAREamistV2` and attempts to solve the
errors.

Note that there is something fishy with the use of `TypeVar` that `mypy`
disagrees with:

```python
src/careamics/careamist_v2.py:128: error: Argument 1 to "_load_model" of "CAREamistV2" has incompatible type "NGConfiguration[CAREAlgorithm] | Path | None"; expected "NGConfiguration[AlgorithmConfig] | Path | None"  [arg-type]
src/careamics/careamist_v2.py:128: error: Argument 1 to "_load_model" of "CAREamistV2" has incompatible type "NGConfiguration[N2NAlgorithm] | Path | None"; expected "NGConfiguration[AlgorithmConfig] | Path | None"  [arg-type]
src/careamics/careamist_v2.py:128: error: Argument 1 to "_load_model" of "CAREamistV2" has incompatible type "NGConfiguration[N2VAlgorithm] | Path | None"; expected "NGConfiguration[AlgorithmConfig] | Path | None"  [arg-type]
Found 3 errors in 1 file (checked 1 source file)
```

One way to solve it to redefine `AlgorithmConfig` in the same module,
rather than importing it. It seems that allows "bounding" the type to
the functions it is used in.

But it would be annoying to have to redefine the generics in every
module. I decided to just ignore it for now for two reasons:
- https://github.com/CAREamics/careamics/pull/817 introduces a validator
that may improve the situation
- Maybe pyright (https://github.com/CAREamics/careamics/pull/698) will
be better suited